### ISSUE TITLE
Question about your merge sort!

### ISSUE THREAD

**Issue by mspanish** [loiane/javascript-datastructures-algorithms#1]
Hello and congrats on your upcoming book! I look forward to it, and am delighted to see that you are a a woman :)

I am just working with merge sort algos for the first time, and see you've got a slightly different thing going on here - the 

result.push(left[il++]);

instead of using result.push(left.shift()) - which seems to be what I've seen elsewhere. Does eliminating the shift() help performance?

thanks for all your samples and best of luck w/ the book launch.

Obrigada desde Alaska
Stacey

**Comment by loiane** [comment]
Thanks Anthony. If you find errors, you can create issues here! Thanks again!

**Comment by ryanpoplin** [comment]
Hey Loiane, thanks for writing this book. It's awesome to be able to jump into the concepts with having to learn all of the mathematical notations in conjunction with C || Java!

**Comment by ryanpoplin** [comment]
without*

**Comment by loiane** [comment]
Thanks Ryan! Hope you like it! :)
