### ISSUE TITLE
Add more Pseudo code

### ISSUE THREAD

**Issue by Code-Blackwell** [loiane/javascript-datastructures-algorithms#10]
I'm a DevCamp student trying to learn DataStructures. Your code is great but is hard to learn  conceptually because of the lack of Pseudocode.

**Comment by loiane** [comment]
Hi, this source code belong to the book JavaScript data structure and algorithms. In the book the concept is explained graphically and the code is presented in JavaScript because the book is about JavaScript so pseudo code is used.
