### ISSUE TITLE
Chapter 10: Possible error found within the code of method fixTreeProperties(node) on page 264

### ISSUE THREAD

**Issue by thinktinker** [loiane/javascript-datastructures-algorithms#106]
The following while condition is not valid as method isRed() shouldn't be invokable through .color.

while (node && node.parent && **node.parent.color.isRed()** && node.color !== Colors.BLACK){
     //rest of the code block in here
}

By the way, I couldn't find the code for chapter 10's RedBlackTree and RedBlackNode anywhere in the downloaded code or in the git repo here. Please advise. Thank You.

**Comment by loiane** [comment]
@thinktinker - thanks for opening the issue. I'll review it and get back to you!

**Comment by loiane** [comment]
fixed in the fourth-ed branch.
