### ISSUE TITLE
Don't need to re-set `items` array

### ISSUE THREAD

**Issue by wruth** [loiane/javascript-datastructures-algorithms#11]
Hi Loiane:

I was just glancing through some of your new ES6 based code — cool stuff! I just learned about this idea of using a `WeakMap` for private data today, partly from your example. I will make one observation in the usage of this in your _01-Stack3.js_ file however. In `push()` and `pop()` you have a pattern where you re-set the array on the `items` `WeakMap` after manipulating it, for instance:

```
            let s = items.get(this);
            s.push(element);
            items.set(this, s);
```

Pretty sure it is unnecessary to set the array `s` after having gotten the reference to it. You didn't `delete` it, so you're just sharing that pointer `s` with the `items` `WeakMap`. That is, it's a pointer (really), not a copy of the array. So you should be able to omit the statement `items.set(this, s);`.

Cheers!

**Comment by loiane** [comment]
Thanks for the PR!
