### ISSUE TITLE
Chapter 4: Possible issue with the parenthesesChecker algorithm. 

### ISSUE THREAD

**Issue by saintpaultinga** [loiane/javascript-datastructures-algorithms#112]
I used the parenthesesChecker algorithm in chapter 4 to check the following expression "(2 * {4 + 3} )" and it returned false. I would like to know if it's an issue or the algorithm only apply to symbols.

Thanks

**Comment by loiane** [comment]
Hi @saintpaultinga this is not a valid expression to test the algorithm. It needs to contain only ({[]}) chars.

**Comment by saintpaultinga** [comment]
Ok, I get it! 
Thanks
