### ISSUE TITLE
Capítulo 7 - Método remove (sondagem linear)

### ISSUE THREAD

**Issue by soaresderik** [loiane/javascript-datastructures-algorithms#113]
Na página 171, da primeira edição, pede para substituir as duas linhas pelo código `table[index] = undefined` quando na primeira ocorrência poderia ser `table[position] = undefined`

Pode ter havido algum equívoco na hora de digitar ou o trecho no livro também é válido?

**Comment by loiane** [comment]
Olá, correto, esse erro faz parte da errata.
