### ISSUE TITLE
Converting binary numbers to decimal

### ISSUE THREAD

**Issue by thiagosantoscunha** [loiane/javascript-datastructures-algorithms#132]
Hello, Loiane!
I'm having difficulty understanding the meaning of 'rem' within the algorithm present in the decimalToBinary () function.

Attention:
**Page** 125, **Language:** Portuguese.

Thanks for the collaboration.

**Comment by guinuxbr** [comment]
Olá colega.

Pude observar que é brasileiro, portanto vou responder em portugues.
O "rem" vem de "remainder" que no contexto significa "resto" da divisão.
