### ISSUE TITLE
Uncaught ReferenceError: printHTMLTree is not defined

### ISSUE THREAD

**Issue by amejias101** [loiane/javascript-datastructures-algorithms#14]
When trying to open chapter08/02-UsingBinarySearchTree.html I keep getting `02-UsingBinarySearchTree.js:56 Uncaught ReferenceError: printHTMLTree is not defined`

**Comment by amejias101** [comment]
@loiane any clue?

**Comment by loiane** [comment]
Hi @amejias101 please ignore this error. This is another js file that was not included in the source code, I used it for my own testing. I deleted the last line of code that made a reference to this error.
