### ISSUE TITLE
tree examples link error

### ISSUE THREAD

**Issue by xgqfrms** [loiane/javascript-datastructures-algorithms#146]
#tree examples link error

> not exist the `chapter10` folder

https://github.com/loiane/javascript-datastructures-algorithms/tree/third-edition/examples/chapter10

![image](https://user-images.githubusercontent.com/7291672/62913174-b5518d00-bdbd-11e9-9d85-f60846f82c13.png)

**Comment by loiane** [comment]
chapter 10 restored, thanks for reporting this issue.
