### ISSUE TITLE
Set's implementation is not rigorous.

### ISSUE THREAD

**Issue by reactjser** [loiane/javascript-datastructures-algorithms#148]
```
class Set {
   ...
}

const s = new Set()
s.add(1)
s.add('1')
console.log(s.size()); // 1
console.log(s.values()); // 1
```

The `1` is not same as `'1'`.

**Comment by Jeffzholy** [comment]
Hi @reactjser yes you are right, but from my perspective the build-from-scratch data structure is for mimicking native Set behaviours and understanding the concept of Set, not for any production use; for sure it can be improved, but not a must, thanks

**Comment by reactjser** [comment]
Thanks for your reply.
