### ISSUE TITLE
Naming in single rotations in AVL tree representation

### ISSUE THREAD

**Issue by ristovskiv** [loiane/javascript-datastructures-algorithms#15]
I think the naming of the functions

```
var rotationLL = function(node) {
    var tmp = node.left;
    node.left = tmp.right;
    tmp.right = node;

    return tmp;
};

var rotationRR = function(node) {
    var tmp = node.right;
    node.right = tmp.left;
    tmp.left = node;

    return tmp;
};
```

is wrong. By my understanding of AVL rotations, the names of the functions actually need to be swapped. So the function `rotationLL` will be `rotationRR` and vice versa. If this is confirmed I don't mind making a PR.

**Comment by loiane** [comment]
Hi, sorry for the delay in replying your message.

The names are correct:
* RR (Right-Right) – it is a single rotation to the left.
* LL (Left-Left) – it is a single rotation to the right.
