### ISSUE TITLE
Typo in 2nd edition, Chapter 8 page 191

### ISSUE THREAD

**Issue by kennetpostigo** [loiane/javascript-datastructures-algorithms#16]
The diagram of the single rotation to the right:

<img width="780" alt="screen shot 2016-08-30 at 11 20 32 am" src="https://cloud.githubusercontent.com/assets/8888991/18095087/d06a3e32-6ea3-11e6-852b-1b8f5c851f18.png">

the unbalanced tree has 60 on the left. Which is wrong because all values larger than 50 go on the right. You seem to have noticed because the balanced tree has 40 instead of 60. So just need to fix the unbalanced tree and change 60 to 40.

**Comment by loiane** [comment]
Thanks for the errata @kennetpostigo - will let the publisher know!
