### ISSUE TITLE
Made some suggestions

### ISSUE THREAD

**Issue by hefeng6500** [loiane/javascript-datastructures-algorithms#178]
Hi loiane

I am the Chinese reader of your book "Learning javascript data structure and algorithm". I am studying the AVL tree and found a line of code in the method of removeNode that is unnecessary, 

link this

 `this.getBalanceFactor(node.left) === BalanceFactor.BALANCED`

Because I think if the tree is balanced, there is no need to move

additionally，I submitted a request in the project , do you have permission to merge the code for me?

PR： [https://github.com/PacktPublishing/Learning-JavaScript-Data-Structures-and-Algorithms-Third-Edition/pull/12](https://github.com/PacktPublishing/Learning-JavaScript-Data-Structures-and-Algorithms-Third-Edition/pull/12)

Looking forward to your response！

**Comment by Jeffzholy** [comment]
Hey @loiane , think this issue is fixed by this PR https://github.com/loiane/javascript-datastructures-algorithms/pull/193. And also @hefeng6500, your issue description is different from the PR that you mentioned in the description. In a word this issue can be safely closed

**Comment by loiane** [comment]
@Jeffzholy thanks!
