### ISSUE TITLE
Submitting algorithms

### ISSUE THREAD

**Issue by anthonycampbell** [loiane/javascript-datastructures-algorithms#179]
Is this repo open for new commits for algorithms that it doesn't already have?

**Comment by loiane** [comment]
Yes!

**Comment by anthonycampbell** [comment]
okay. I implemented the gale-shapley algorithm. It solves the stable matching problem. Here is a link to its wiki page: https://en.wikipedia.org/wiki/Gale%E2%80%93Shapley_algorithm 

Should I just make a pull request?

**Comment by loiane** [comment]
@anthonycampbell yes, please.
