### ISSUE TITLE
e a issue about npm run serve

### ISSUE THREAD

**Issue by WellAlreadyTaken** [loiane/javascript-datastructures-algorithms#184]
i just start ,step by step 
then i got this problem
look like that
![屏幕截图 2021-11-24 142635](https://user-images.githubusercontent.com/34592132/143186129-57800486-c9ef-42b7-b477-5b2a749978e3.png)
it seem a problem abot webpack? nodejs?

**Comment by loiane** [comment]
Hi, yes, this looks like a webpack issue. Will check with the publisher if this can be updated and released.
