### ISSUE TITLE
Insert function of circular-linked-list in charpter6 is error

### ISSUE THREAD

**Issue by SHIJIECHN** [loiane/javascript-datastructures-algorithms#186]
[circular-linked-list.js](https://github.com/loiane/javascript-datastructures-algorithms/blob/main/src/js/data-structures/circular-linked-list.js)
error: current = this.getElementAt(this.size());
answer: current = this.getElementAt(this.size() - 1);

**Comment by carlos-novaes** [comment]
> [circular-linked-list.js](https://github.com/loiane/javascript-datastructures-algorithms/blob/main/src/js/data-structures/circular-linked-list.js) error: current = this.getElementAt(this.size()); answer: current = this.getElementAt(this.size() - 1);

it took me almost an hour to figure it out, I'm glad that I wasn't the only one that got it :D

**Comment by loiane** [comment]
@carlos-novaes @SHIJIECHN can you please open a PR with this fix?
Thanks for the pointing it out!

**Comment by Jeffzholy** [comment]
@loiane don't have an access to push up a branch for opening a PR, how to open a PR correctly?

**Comment by loiane** [comment]
@Jeffzholy thank you, merged.
