### ISSUE TITLE
Incorrect return value of Kruskal

### ISSUE THREAD

**Issue by tequ1lAneio** [loiane/javascript-datastructures-algorithms#204]
Hi, @loiane 

I found an unexpected result of Kruskal for getting MST.
see https://github.com/loiane/javascript-datastructures-algorithms/blob/main/examples/chapter12/07-Kruskal.js#L18

When running the code above, the return value is `[2, 2, 4, 2, 2]` instead of the expected result `[2, 2, 2, 2, 2]`. 
Could you take a look at it? Thanks!

**Comment by loiane** [comment]
Prim and Kruskal can have different results. It all depends on the algorithm, both would be valid results.
