### ISSUE TITLE
Why is the hash-table doesn't implement by an array?

### ISSUE THREAD

**Issue by JackZong** [loiane/javascript-datastructures-algorithms#209]
Hi team,

I saw that the hash-table is implemented by an `Object {}` not the `Array []`, is this by design? It seems that the `Array` type data structure can provide a better search efficiency.

<img width="621" alt="image" src="https://user-images.githubusercontent.com/12573233/185588287-4aaaa370-a357-4f50-8a50-43e786f28ab5.png">

file at:
https://github.com/loiane/javascript-datastructures-algorithms/blob/7d33c7ccf5185144e9ab561f152cda841ab86f22/src/ts/data-structures/hash-table.ts

Bests,
Jackson

**Comment by loiane** [comment]
The original idea was to mimic the Set data structure.
I'm reviewing all the code and this is being fixed in this branch: https://github.com/loiane/javascript-datastructures-algorithms/tree/fourth-edition-draft
