### ISSUE TITLE
Chapter 12: toposort, copy for result.finished?

### ISSUE THREAD

**Issue by 3vinicius** [loiane/javascript-datastructures-algorithms#220]
Is the variable `ftime` supposed to be used as a copy for `result.finished` in toposort?

What happens is that when I simply assign `ftimes = result.finished`, the value of `finished` is changed. So, I decided to use `Object.assign({}, result.finished)`, which creates a copy of the object.

**Comment by loiane** [comment]
if you plan to modify the result, then a copy would be preferred. It all depends on what you are doing with the result you received as an output.
