### ISSUE TITLE
Stack Modular e com Arrow functions

### ISSUE THREAD

**Issue by wdiasvargas** [loiane/javascript-datastructures-algorithms#24]
Professora estou no capitulo 3 do seu livro na parte de Stacks
estou tendo problemas em fazer de forma modular
segue o gist  
https://gist.github.com/wdiasvargas/a659a9b36599c323fc3425a94072b4f8

**Comment by loiane** [comment]
Na verdade cada método precisa pertencer à sua própria classe. Separar os métodos em módulos para esse caso em específico não faz muito sentido.
