### ISSUE TITLE
HashCollisionLinearProbing cannot remove elements with same hash

### ISSUE THREAD

**Issue by JeremyFan** [loiane/javascript-datastructures-algorithms#26]
1.Very similar to #23 
```
hash.remove('Jonathan')
hash.remove('Jamie')
```
As the position Jonathan being undefined, Jamie cannot be removed. 

2.There is an endless loop in testcase `08-UsingHashCollisionLinearProbing.js`
```
hashLinearProbing.remove('Gandalf');
hashLinearProbing.get('Gandalf')
```
The position of Gandalf was undefined, but the loop will continue till find Gandalf.

**Comment by loiane** [comment]
Thanks! I'll take a look and get back to you.
I need to rewrite this algorithm with a cache approach.

**Comment by loiane** [comment]
Hi,
Added 2 versions of this algorithm with the fixes:
* Version 1: Update hash after each deletion: https://github.com/loiane/javascript-datastructures-algorithms/blob/third-edition/src/js/data-structures/hash-table-linear-probing.js
* Version 2: Soft delete: https://github.com/loiane/javascript-datastructures-algorithms/blob/third-edition/src/js/data-structures/hash-table-linear-probing-lazy.js

Also added some tests with Mocha to make sure different scenarios were covered:
* Version 1: https://github.com/loiane/javascript-datastructures-algorithms/blob/third-edition/test/js/data-structures/hash-table-linear-probing.spec.js
* Version 2: https://github.com/loiane/javascript-datastructures-algorithms/blob/third-edition/test/js/data-structures/hash-table-linear-probing-lazy.spec.js
