### ISSUE TITLE
Deletion of a key in hash table (with linear probing) is wrong

### ISSUE THREAD

**Issue by prashanth1509** [loiane/javascript-datastructures-algorithms#30]
First of all, liked the simplicity of the book and its neat for beginners.

So the issue is about the deletion in hash table being described in the book.

https://github.com/loiane/javascript-datastructures-algorithms/blob/10b24fd4a3ec01aa8db5a5bffb29e55559647dae/chapter07/07-HashCollisionLinearProbing.js#L73

Deletion of a key in hash table (with linear probing) is not straightforward.

To clarify, consider this example:

> 
> Let's say we have an array of length 2 as hash table and a simple bad hash function. 
> function hash(n) { return n % 2; }
> 
> and lets have two keys 2, 4.
> At first, 2 goes into 0th index.
> Then 4 has collision and will go into 1st index.
> 

Now deleting 2 will mark 0th index as undefined and then searching for key 4 will not work because we search only till undefined or the value.
https://github.com/loiane/javascript-datastructures-algorithms/blob/10b24fd4a3ec01aa8db5a5bffb29e55559647dae/chapter07/07-HashCollisionLinearProbing.js#L49

To fix it, my suggestion would be to use soft deletion like replacing 0th index with some special value to mark as empty, otherwise the probing will stop over there.

For clarification pls refer Deletion section in https://en.wikipedia.org/wiki/Linear_probing.

**Comment by loiane** [comment]
Thanks for the example!
I need to rewrite this algorithm with a better approach!

**Comment by loiane** [comment]
Hi,
Added 2 versions of this algorithm with the fixes:
* Version 1: Update hash after each deletion: https://github.com/loiane/javascript-datastructures-algorithms/blob/third-edition/src/js/data-structures/hash-table-linear-probing.js
* Version 2: Soft delete: https://github.com/loiane/javascript-datastructures-algorithms/blob/third-edition/src/js/data-structures/hash-table-linear-probing-lazy.js

Also added some tests with Mocha to make sure different scenarios were covered:
* Version 1: https://github.com/loiane/javascript-datastructures-algorithms/blob/third-edition/test/js/data-structures/hash-table-linear-probing.spec.js
* Version 2: https://github.com/loiane/javascript-datastructures-algorithms/blob/third-edition/test/js/data-structures/hash-table-linear-probing-lazy.spec.js
