### ISSUE TITLE
Truthy and falsy - Result of value type(string) is wrong

### ISSUE THREAD

**Issue by brunokratka** [loiane/javascript-datastructures-algorithms#31]
On topic 'Truthy and falsy' chapter 1, both editions;

The description of value type(string) which you can see on example:

> The result is false if the string is empty (length is 0); otherwise, the result is true (**length > 1**).

Can be verify on output as **true** when val.length is 1. Using the same function example, below the table of truthy and falsy,  we can see:

```javascript
function testTruthy(val){
    return val ? console.log('truthy') : console.log('falsy');
}

testTruthy('a');  //true
```

**Comment by loiane** [comment]
Thanks Bruno! Will review it and get back to you.

**Comment by loiane** [comment]
Errata submitted for both editions. Exampled added and text will be corrected in next ed.
