### ISSUE TITLE
Chapter 6 Sets code does not work

### ISSUE THREAD

**Issue by saidbakr** [loiane/javascript-datastructures-algorithms#32]
I have the following code that I have get till page 94 of the first edition:

```JavaScript
function Set() {
    var items = {};
    
    this.has = function(value) {
        return items.hasOwnProperty(value);
    }
    this.add = function(value){
        if(!this.has(value)){
            items[value] = value;
            return true;
        }
        return false;
    }    
}

var set = new Set();
set.add(1);
set.add(5);
set.add(10);
console.log(set.items); //undefined
```
The `console.log` outputs `undefined`. I'm using Google Chrome Version 62.0.3202.75 64 bit on Ubuntu linux and my files structure is two files:
 1. index.html
 2. js.js

**Comment by loiane** [comment]
Hi @saidbakr, because it was used functions, the items is a private variable, so it cannot be accessed directly. To console.log the items, you need to add the getItems function as demonstrated here: https://github.com/loiane/javascript-datastructures-algorithms/blob/first-edition/chapter06/01-Set.js#L76

**Comment by saidbakr** [comment]
@loiane 
Hi,
As I know from OOP. `items` is a public property of the class `Set` and `items` has global scope in its class. Hence, any instance object of this class should inherit its public property `items` and it should be public too. i.e at least `console.log(set.items)` returns null but not undefined.
I think the code in the book is correct as it is. The question is: Why it does not work in my browser?

**Comment by loiane** [comment]
Hi @saidbakr, this code is not really OO, is uses closures from JavaScript. In this particular case the var items is private to the function scope only.
If you use the class syntax from ES6 or the prototype from JS, then the items variable will be public.
