### ISSUE TITLE
Ch. 2 Array.from

### ISSUE THREAD

**Issue by mangotrader** [loiane/javascript-datastructures-algorithms#36]
Thanks for the excellent book! 

I'm a bit puzzled by the Array.from() usage example at the bottom of Page 63 in 2nd version. It was said that the returned array will be the even values, while the second param of the Array.from() function is actually a map function instead of a filter function. So the resulting array will be [true, false, true, ..., ].

Is my assumption correct?

**Comment by loiane** [comment]
Hi @mangotraderm, your assumption is correct. The correct text would be it will return an array with value "true" if in the original array the number is even, and false otherwise. I'll submit an errata for this. Thanks for opening the issue!
