### ISSUE TITLE
Ch.3 Linked Lists indexOf

### ISSUE THREAD

**Issue by mangotrader** [loiane/javascript-datastructures-algorithms#37]
Hello Loiane, I think there's a small bug in the indexOf function in page 112 in the 2nd edition book. 

let index = -1 should be let index = 0, so that in the while loop later, when the element is found, the function returns the correct index. Otherwise the function will return -1 if the first element is found.

What would you think?

**Comment by loiane** [comment]
Hi @mangotrader - that is correct. This was raised as an errata and the code has been updated: https://github.com/loiane/javascript-datastructures-algorithms/blob/master/chapter05/01-LinkedList.js#L110
