### ISSUE TITLE
Adelson-Velskii and Landis' tree

### ISSUE THREAD

**Issue by georgejdli** [loiane/javascript-datastructures-algorithms#4]
The js source files for the AVL tree example are empty.

**Comment by thinktinker** [comment]
Any updates to the resources for chapter 10? The folder is empty.
Was referring to the code from this chapter, turns out there's a bug in removeNode in the self-balancing tree (AVLTree).

Please advise.

**Comment by loiane** [comment]
@thinktinker the source has been added: https://github.com/loiane/javascript-datastructures-algorithms/blob/master/src/js/data-structures/avl-tree.js

**Comment by loiane** [comment]
@thinktinker can you point to the bug pls? I'll take a look at the test cases to include a scenario for it to reproduce it.

**Comment by thinktinker** [comment]
Hi Loiane.
The *problem* *happens from rotationRR when performing a remove() in the
AVLTree*.
The error produced is: *TypeError: Cannot read property 'right' of
undefined*
My assumption is that the 'self-balancing process' after removing a value
ran into issues.

*The below is the scenario, which I've attached the working folder as well:*

//1. Using Babel, I ran starter.js that points to and file test-avl-tree.js
//2. In test-avl-tree.js, I created an instance of AVLTree and inserted
some values
const jsavltree = new AVLTree();
jsavltree.insert(10);
jsavltree.insert(30);
jsavltree.insert(20);
jsavltree.insert(15);
jsavltree.insert(35);
jsavltree.insert(25);
jsavltree.insert(28);

const printNode = (value) => console.log(value);
const inorder = jsavltree.inOrderTraverse(printNode);

//3. Upon trying to remove the value 30, the error occurs: *TypeError:
Cannot read property 'right' of undefined*
*jsavltree.remove(30);*
const inorder2 = jsavltree.inOrderTraverse(printNode);

Please advise further. Thanks.
