### ISSUE TITLE
The link for colorful chart  can't open !

### ISSUE THREAD

**Issue by angelpray** [loiane/javascript-datastructures-algorithms#42]
[https://www.packtpub.com/sites/default/files/downloads/LearningJavaScriptDataStructuresandAlgorithmsSecondEdition_ColorImages.pdf](url)
![image](https://user-images.githubusercontent.com/17873970/37407929-fadb536c-27d5-11e8-82e3-ffd7df1718b3.png)
Is it my computer's problem?

**Comment by loiane** [comment]
Hi @angelpray, please try again: [https://www.packtpub.com/sites/default/files/downloads/LearningJavaScriptDataStructuresandAlgorithmsSecondEdition_ColorImages.pdf](https://www.packtpub.com/sites/default/files/downloads/LearningJavaScriptDataStructuresandAlgorithmsSecondEdition_ColorImages.pdf)

**Comment by loiane** [comment]
In case you need the pdf, it is also available here:
[LearningJavaScriptDataStructuresandAlgorithmsSecondEdition_ColorImages.pdf](https://github.com/loiane/javascript-datastructures-algorithms/files/1820598/LearningJavaScriptDataStructuresandAlgorithmsSecondEdition_ColorImages.pdf)
