### ISSUE TITLE
Circular linked list if statement evaluation

### ISSUE THREAD

**Issue by diegocasmo** [loiane/javascript-datastructures-algorithms#5]
I was wondering if anyone could explain to me why in the circular linked list example, on the ``insert`` method, why is it necessary to check if ``current.next`` is ``null``. When exactly could ``node.next`` be ``null``, if the tail of the linked list always keeps a reference to head?

```
if (node.next === null){ //update in case last element
  node.next = head;
}
```

**Comment by loiane** [comment]
This is in case the first element is also the last element - first insertion

**Comment by diegocasmo** [comment]
If the first element is also the last element on the list (first insertion), wouldn't that case fall under the first section of the if statement evaluation (``position === 0``), since we already evaluated (``position >= 0 && position <= length``), and therefore, the position must be less or equal to the length of the list, which in the case of the first insertion it will be equal to ``0``?

**Comment by loiane** [comment]
Hi Diego, sorry for the late reply, I'm reviewing all the source code and reviewed this case. The condition is really not needed. Changed source code.
