### ISSUE TITLE
A minor mistake in Chapter 5

### ISSUE THREAD

**Issue by richardmyu** [loiane/javascript-datastructures-algorithms#78]
Thanks for the excellent book! 
I found a minor mistake in chapter05/03-DoublyLinkedList2.js :

insert(){
  if () {
    if () {
    ...
    } else if (position === this.size()) {
       //error
      current = tail;
       //ok
      current = this.getTail();
    } else {
    ...
    }
  }
}

**Comment by loiane** [comment]
Thanks @richardmyu - this has been fixed in the newest edition of the book. Source code is available at the master branch

**Comment by maxim-xu** [comment]
@loiane Hi Loiane. Thank you for this great book!

it seems that in the current Graph implementation, one can add duplicate edges to the adjacency list - is this expected?  Thank you!

**Comment by loiane** [comment]
@maxim-xu You are correct, let me review the code to prevent this behavior. Thanks for pointing it out!

**Comment by loiane** [comment]
Fixed in this branch: https://github.com/loiane/javascript-datastructures-algorithms/tree/fourth-edition-draft
